### ISSUE TITLE
Support the multi domain and multi database already ?

### ISSUE THREAD

**Issue by heartshare** [plugins-world/DcatSaas#1]
https://github.com/mouyong/saas-skeleton like this 
支持多数据库，每个租户拥有独立的数据库
 支持多域名，每个租户可以配置多个域名
 
已支持了ma？ 🙏🏻

**Comment by mouyong** [comment]
没理解。ma是指的什么呢？

dcatsaas，是支持最新的laravel框架。 
saas-skeleton 是某个laravel框架的模板。 

推荐使用plugins-world/laravelsaas。支持最新的laravel框架，并且减少了对dcatsaas的依赖。更加适合噢

**Comment by heartshare** [comment]
root@086993d52d1b:/var/www/public/saas# php artisan market:require master.zip 
Install fail: Array to string conversion
root@086993d52d1b:/var/www/public/saas# php artisan market:require plugins-world/dcat-saas
Install fail: Array to string conversion
請問一下是什麼問題？ (running in Laradock  docker LNMP)

**Comment by mouyong** [comment]
@heartshare 可以提供一下日志吗， Array to string conversion 应该是某个地方处理错误

**Comment by heartshare** [comment]
![image](https://github.com/plugins-world/DcatSaas/assets/919188/71e48634-ac11-42ae-b25b-83fb74e9e338)

**Comment by mouyong** [comment]
> root@086993d52d1b:/var/www/public/saas# php artisan market:require master.zip Install fail: Array to string conversion root@086993d52d1b:/var/www/public/saas# php artisan market:require plugins-world/dcat-saas Install fail: Array to string conversion 請問一下是什麼問題？ (running in Laradock docker LNMP)

@heartshare 这个问题是因为插件管理器曾经做过升级：插件的 plugins.json 里面，unikey 需要改成 fskey，插件未更改，导致的。

已复现，已修复，更新插件管理器，然后重新执行安装就可以了。下方是安装成功的截图。
更新插件管理器，项目跟目录执行：`composer require fresns/plugin-manager`
重新安装 laravel 插件：`php artisan market:requre plugins-world/dcat-saas`

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/65c0742e-2d91-401a-893a-edb0e4da4d41)

**Comment by mouyong** [comment]
> @heartshare 可以提供一下日志吗， Array to string conversion 应该是某个地方处理错误

没有提示的问题也解决了。后续遇到无法安装，会提示出具体原因。需要更新插件管理器。

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/cf0014d6-bfa9-4742-86e8-3fbd4eaf3769)

**Comment by mouyong** [comment]
安装成功后：

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/43463570-0f73-4dd0-85da-ea798d2ddc67)

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/db0c7476-ad46-4308-98bc-04239544a25b)

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/140c22d8-cf14-46da-938d-c8208c2267c5)

![image](https://github.com/plugins-world/DcatSaas/assets/10336437/aa6c2218-8de5-4d83-86ba-eacbc3444539)

**Comment by mouyong** [comment]
需要注意，使用的时候手动修改下 vendor 包的相关文件。dcat-saas 官方的 bug. 会导致无法访问。

见说明：https://github.com/jqhph/dcat-admin/pull/2038#issue-1740045935

见文件修复变更：https://github.com/jqhph/dcat-admin/pull/2038/files

**Comment by heartshare** [comment]
Very details. I try again, Thanks

**Comment by heartshare** [comment]
Fixed already , can login dcatadmin and show tenant list. Thanks 
root@b35136fcce0a:/var/www/saas# php artisan saas:tenant-list 
Listing all tenants.
[Tenant] id: apple @ apple.saas.local

**Comment by mouyong** [comment]
OK.
